#!/usr/bin/env bash
# The script loops from 1 to 10 and displays bad luck on the 4th loop, good luck on the 8th loop, and Best School otherwise.

i=0
while (( i < 10 ))
do
	i=$(( i + 1 ))
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
