#!/usr/bin/env bash
# Script displays the time for 12 hours and 59 minutes.

H=0
while (( H <= 12 ))
do
	echo "Hour: $H"
	H=$(( H + 1 ))
	M=1
	while (( M <= 59 ))
	do
		echo "$M"
		M=$(( M + 1 ))
	done
done
