#!/usr/bin/env bash
# UWU HAP

apt-get update
apt-get -y upgrade
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
defaults
    mode    http
frontend http-in
    bind    *:80
    default_backend servers
backend servers
    balance roundrobin
    server  4282-web-01 52.47.102.31:80 check
    server  4282-web-02 13.38.104.67:80 check
EOT
sudo service haproxy restart